In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("iris.csv")
df

    sepal_length sepal_width petal_length petal_width          flower
0            5.1         3.5          1.4         0.2     Iris-setosa
1            4.9         3.0          1.4         0.2     Iris-setosa
2            4.7         3.2          1.3         0.2     Iris-setosa
3            4.6         3.1          1.5         0.2     Iris-setosa
4            5.0        -3.6         -1.4         0.2     Iris-setosa
..           ...         ...          ...         ...             ...
145          6.7         3.0          5.2         2.3  Iris-virginica
146          6.3         2.5          5.0         1.9  Iris-virginica
147          6.5         3.0          5.2         2.0  Iris-virginica
148          6.2         3.4          5.4         2.3  Iris-virginica
149          5.9         3.0          5.1         1.8  Iris-virginica

[150 rows x 5 columns]

In [4]:
df.drop(columns=['flower']) #Drop flower column

    sepal_length sepal_width petal_length petal_width
0            5.1         3.5          1.4         0.2
1            4.9         3.0          1.4         0.2
2            4.7         3.2          1.3         0.2
3            4.6         3.1          1.5         0.2
4            5.0        -3.6         -1.4         0.2
..           ...         ...          ...         ...
145          6.7         3.0          5.2         2.3
146          6.3         2.5          5.0         1.9
147          6.5         3.0          5.2         2.0
148          6.2         3.4          5.4         2.3
149          5.9         3.0          5.1         1.8

[150 rows x 4 columns]

In [10]:
# Strategy 1: Different strategies for each column
df_st1 = df.copy()

# Convert numerical columns to float
for col in ['sepal_length', 'sepal_width', 'petal_length', 'petal_width']:
    df_st1[col] = pd.to_numeric(df_st1[col], errors='coerce')


# fill with mean
df_st1['sepal_length'] = df_st1['sepal_length'].fillna(df_st1['sepal_length'].mean())

# fill with median
df_st1['sepal_width'] = df_st1['sepal_width'].fillna(df_st1['sepal_width'].median())

# fill with zero
df_st1[['petal_length', 'petal_width']] = df_st1[['petal_length', 'petal_width']].fillna(0)

In [11]:
df_st1.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
flower          0
dtype: int64

In [12]:
 # Strategy 2: Fill with median of each column
df_median = df.copy()
# Convert all numeric columns to float
for col in ['sepal_length', 'sepal_width', 'petal_length', 'petal_width']:
    df_median[col] = pd.to_numeric(df_median[col], errors='coerce')

df_median = df_median.fillna(df_median.median(numeric_only=True))

In [13]:
df_median.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
flower          0
dtype: int64